name: Validate
on:
  pull_request:
  workflow_call:
  push:
    branches:
      - main

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - run: deno check .
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
      - run: deno test --coverage
        working-directory: lib
      - run: deno coverage
        working-directory: lib
      - run: deno coverage --detailed
        working-directory: lib
